# Generated by Django 3.2.4 on 2021-06-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0003_auto_20210626_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
